### ISSUE TITLE
Remove verbose and debug log level filtering in release lib?

### ISSUE THREAD

**Issue by antoine-dbr** [inrista/loggliest#1]
Hi,

First thanks for your library that allowed us to boot strap loggly in our Android app very quickly!

Quick request, is is possible to remove those if(BuildConfig.DEBUG) in those Loggly.v() and Loggly.d() calls since the app deployed in JCenter is built in release mode?

In any case, I can do it in my copy of the source or do a pull request. I was just thinking other library users may benefit from it.

My reasoning behind it / use-case is that we can control the iOS and Android log-level server-side e.g. we start logging info and above by default but if a device starts to misbehave, we can turn on high-granularity verbose / debug logging for that particular device to facilitate debugging.

Since that decision is made at the app-level, no need to filter it on the library (just adding a note in the javadoc that this will emit a log of logging and battery / data and loggly storage usage will increase so it should used carefully^^).

Please let me know if this is a valid request.

Thanks,
-Antoine

**Comment by inrista** [comment]
I Agree. It makes sense to leave this decision to the app and not force filtering in the library. Anyways, just the fact that the JCenter-deployed jar always drops all debug and verbose messages is reason enough to remove this since this is the way most people probably will use the library... I'll fix it and create a new release.

**Comment by inrista** [comment]
Removed in v0.2

**Comment by antoine-dbr** [comment]
Sweet, thanks!
